In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
cars_raw = read_csv("serbia_car_sales_price_2024.csv")

Rows: 8413 Columns: 18
── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (11): post_info, car_name, A/C, emission_class, horsepower, color, type_...
dbl  (7): views, favorite, price, year, seats_amount, car_mileage, km, engin...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [3]:
head(cars_raw)

  views favorite post_info          price car_name        year A/C
1  58   0        posted a week ago  1100  Alfa Romeo 11.9 2002 NA
2  55   0        posted 2 days ago  1100  Alfa Romeo 145  2000 manual A/C
3 136   4        posted 2 weeks ago  950  Alfa Romeo 145  1999 manual A/C
4 209   1        posted 4 weeks ago  500  Alfa Romeo 146  2000 manual A/C
5  61   0        posted 2 days ago   111  Alfa Romeo 147  2024 automatic A/C
6 196   2        posted 4 weeks ago 2300  Alfa Romeo 147  2008 no A/C
  emission_class seats_amount horsepower     color car_mileage, km
1 NA             NA           NA             NA        NA
2 Euro 3          5           106 HP (78 kW) gray  158546
3 Euro 3          5           105 HP (77 kW) green 337000
4 Euro 3          5           120 HP (88 kW) gray  200000
5 NA              5           116 HP (85 kW) gray  280000
6 NA              5           105 HP (77 kW) black 188000
  engine_capacity, cc type_of_drive doors     fuel         car_type
1   NA                NA            NA        NA           NA
2 1400                front         2/3 doors petrol + gas hatchback
3 1910                front         2/3 doors diesel       hatchback
4 1600                front         4/5 doors petrol + gas limousine
5 1900                front         2/3 doors diesel       hatchback
6 1600                front         4/5 doors petrol + gas hatchback
  gearbox
1 NA
2 manual, 5 speeds
3 manual, 5 speeds
4 manual, 5 speeds
5 manual, 5 speeds
6 manual, 5 speeds

In [4]:
str(cars_raw)

spc_tbl_ [8,413 × 18] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ views              : num [1:8413] 58 55 136 209 61 ...
 $ favorite           : num [1:8413] 0 0 4 1 0 2 1 6 16 0 ...
 $ post_info          : chr [1:8413] "posted a week ago" "posted 2 days ago" "posted 2 weeks ago" "posted 4 weeks ago" ...
 $ price              : num [1:8413] 1100 1100 950 500 111 2300 3500 2150 1350 2000 ...
 $ car_name           : chr [1:8413] "Alfa Romeo 11.9" "Alfa Romeo 145" "Alfa Romeo 145" "Alfa Romeo 146" ...
 $ year               : num [1:8413] 2002 2000 1999 2000 2024 ...
 $ A/C                : chr [1:8413] NA "manual A/C" "manual A/C" "manual A/C" ...
 $ emission_class     : chr [1:8413] NA "Euro 3" "Euro 3" "Euro 3" ...
 $ seats_amount       : num [1:8413] NA 5 5 5 5 5 5 5 5 5 ...
 $ horsepower         : chr [1:8413] NA "106 HP (78 kW)" "105 HP (77 kW)" "120 HP (88 kW)" ...
 $ color              : chr [1:8413] NA "gray" "green" "gray" ...
 $ car_mileage, km    : num [1:8413] NA 158546 337000 200000 280000 ...
 $ engine_capacity, cc: num [1:8413] NA 1400 1910 1600 1900 ...
 $ type_of_drive      : chr [1:8413] NA "front" "front" "front" ...
 $ doors              : chr [1:8413] NA "2/3 doors" "2/3 doors" "4/5 doors" ...
 $ fuel               : chr [1:8413] NA "petrol + gas" "diesel" "petrol + gas" ...
 $ car_type           : chr [1:8413] NA "hatchback" "hatchback" "limousine" ...
 $ gearbox            : chr [1:8413] NA "manual, 5 speeds" "manual, 5 speeds" "manual, 5 speeds" ...
 - attr(*, "spec")=
  .. cols(
  ..   views = col_double(),
  ..   favorite = col_double(),
  ..   post_info = col_character(),
  ..   price = col_double(),
  ..   car_name = col_character(),
  ..   year = col_double(),
  ..   `A/C` = col_character(),
  ..   emission_class = col_character(),
  ..   seats_amount = col_double(),
  ..   horsepower = col_character(),
  ..   color = col_character(),
  ..   `car_mileage, km` = col_double(),
  ..   `engine_capacity, cc` = col_double(),
  ..   type_of_drive = col_character(),
  ..   doors = col_character(),
  ..   fuel = col_character(),
  ..   car_type = col_character(),
  ..   gearbox = col_character()
  .. )
 - attr(*, "problems")=<externalptr>

In [5]:
summary(cars_raw)

     views            favorite        post_info             price
 Min.   :    0.0   Min.   :  0.000   Length:8413        Min.   :  100
 1st Qu.:   61.0   1st Qu.:  0.000   Class :character   1st Qu.: 1600
 Median :  114.0   Median :  1.000   Mode  :character   Median : 3300
 Mean   :  308.7   Mean   :  2.672                      Mean   : 4848
 3rd Qu.:  245.0   3rd Qu.:  3.000                      3rd Qu.: 5950
 Max.   :27770.0   Max.   :151.000                      Max.   :82000

   car_name              year          A/C            emission_class
 Length:8413        Min.   :1960   Length:8413        Length:8413
 Class :character   1st Qu.:2003   Class :character   Class :character
 Mode  :character   Median :2006   Mode  :character   Mode  :character
                    Mean   :2006
                    3rd Qu.:2010
                    Max.   :2024

  seats_amount   horsepower           color           car_mileage, km
 Min.   :2.00   Length:8413        Length:8413        Min.   :1.000e+00
 1st Qu.:5.00   Class :character   Class :character   1st Qu.:1.767e+05
 Median :5.00   Mode  :character   Mode  :character   Median :2.200e+05
 Mean   :4.94                                         Mean   :2.852e+06
 3rd Qu.:5.00                                         3rd Qu.:2.700e+05
 Max.   :9.00                                         Max.   :4.295e+09
 NA's   :10                                           NA's   :9
 engine_capacity, cc type_of_drive         doors               fuel
 Min.   :  100       Length:8413        Length:8413        Length:8413
 1st Qu.: 1400       Class :character   Class :character   Class :character
 Median : 1700       Mode  :character   Mode  :character   Mode  :character
 Mean   : 1725
 3rd Qu.: 1995
 Max.   :10000
 NA's   :10
   car_type           gearbox
 Length:8413        Length:8413
 Class :character   Class :character
 Mode  :character   Mode  :character

In [6]:
problems(cars_raw)

     row col expected actual file

In [7]:
cars_raw <- cars_raw %>%
rename(post_date=post_info, price_eur=price, ac=`A/C`, mileage_km=`car_mileage, km`, engine_capacity_cc=`engine_capacity, cc`)

In [8]:
cars_raw <- cars_raw %>%
mutate(across(c(views, favorite, price_eur, year, seats_amount, mileage_km, engine_capacity_cc), as.integer))

Warning message:
"There was 1 warning in `mutate()`.
ℹ In argument: `across(...)`.
Caused by warning:
! NAs introduced by coercion to integer range"

#### Cleaning and formatting post_date column

In [9]:
cars_raw <- cars_raw %>%
mutate(post_date = str_remove(post_date, "^(posted|updated)\\s?"))

In [10]:
sum(is.na(cars_raw$post_date))

cars_raw %>%
distinct(post_date)

[1] 0

   post_date
1  a week ago
2  2 days ago
3  2 weeks ago
4  4 weeks ago
5  5 days ago
6  6 days ago
7  3 weeks ago
8  yesterday
9  3 days ago
10 4 days ago
11 today
12 month ago

#### Cleaning AC column

In [11]:
sum(is.na(cars_raw$ac))

cars_raw %>%
distinct(ac)

[1] 10

  ac
1 NA
2 manual A/C
3 automatic A/C
4 no A/C

In [24]:
cars_raw <- cars_raw %>%
mutate(ac = str_trim(str_remove(ac, "A/C$")))

In [13]:
cars_raw <- cars_raw %>%
mutate(emission_class = str_remove(emission_class, "^Euro\\s?")) %>%
mutate(emission_class = as.integer(emission_class))

In [14]:
cars_raw <- cars_raw %>%
mutate(horsepower = str_extract(horsepower, "^[0-9]+") %>% as.numeric()) %>%
mutate(horsepower = as.integer(horsepower))

In [25]:
cars_raw <- cars_raw %>%
mutate(doors = str_trim(str_remove(doors, "doors$")))

In [16]:
cars_raw %>%
distinct(color)

# Color names are OK

   color
1  NA
2  gray
3  green
4  black
5  white
6  red
7  brown
8  silver
9  teget
10 blue
11 golden
12 cream
13 bordeaux
14 turquoise
15 yellow
16 beige
17 multicolored
18 purple
19 orange
20 pink

In [17]:
cars_raw %>%
count(gearbox, sort = TRUE)

  gearbox                 n
1 manual, 5 speeds        4645
2 manual, 6 speeds        2323
3 automatic               1164
4 manual, 4 speeds         168
5 semi-automatic            85
6 manual, multiple speeds   18
7 NA                        10

In [19]:
cars_raw <- cars_raw %>%
  mutate(
    # Kettéválasztjuk a vessző mentén (ha nincs vessző, a 'speeds_raw' NA lesz)
    speeds_raw = str_split_i(gearbox, ", ", 2),
    gearbox = str_split_i(gearbox, ", ", 1),
    
    
    # Kiszedjük a számot a 'speeds_raw' oszlopból, ha nincs szám, akkor 0
    speeds = str_extract(speeds_raw, "[0-9]+") %>% as.numeric(),
    speeds = ifelse(is.na(speeds), 0, speeds)
  ) %>%
  select(-speeds_raw) %>%
  mutate(speeds = as.integer(speeds))

In [ ]:
cars_raw %>%
count(car_name, sort = TRUE)

In [20]:
cars_raw

     views favorite post_date   price_eur car_name            year ac
1      58   0       a week ago  1100      Alfa Romeo 11.9     2002 NA
2      55   0       2 days ago  1100      Alfa Romeo 145      2000 manual
3     136   4       2 weeks ago  950      Alfa Romeo 145      1999 manual
4     209   1       4 weeks ago  500      Alfa Romeo 146      2000 manual
5      61   0       2 days ago   111      Alfa Romeo 147      2024 automatic
6     196   2       4 weeks ago 2300      Alfa Romeo 147      2008 no
7     133   1       5 days ago  3500      Alfa Romeo 147      2008 automatic
8     290   6       6 days ago  2150      Alfa Romeo 147      2008 manual
9    2629  16       a week ago  1350      Alfa Romeo 147      2008 automatic
10     89   0       a week ago  2000      Alfa Romeo 147      2007 no
11     64   0       a week ago  2500      Alfa Romeo 147      2007 no
12   1265  17       a week ago   900      Alfa Romeo 147      2007 automatic
13    117   2       3 weeks ago 2250      Alfa Romeo 147      2007 automatic
14    104   4       a week ago  1950      Alfa Romeo 147      2006 manual
15    736  16       2 weeks ago  700      Alfa Romeo 147      2006 manual
16     42   0       2 days ago  1000      Alfa Romeo 147      2005 no
17    422   4       a week ago  3999      Alfa Romeo 147      2005 automatic
18    178   4       4 weeks ago 2000      Alfa Romeo 147      2004 no
19     90   1       a week ago  1800      Alfa Romeo 147      2004 manual
20    180   2       6 days ago  1000      Alfa Romeo 147      2004 manual
21    202   6       4 weeks ago 1599      Alfa Romeo 147      2004 automatic
22    469   4       2 weeks ago  700      Alfa Romeo 147      2004 manual
23    158   3       yesterday    550      Alfa Romeo 147      2003 manual
24    388  14       3 weeks ago  700      Alfa Romeo 147      2003 manual
25     36   0       3 days ago  1300      Alfa Romeo 147      2003 manual
26    113   0       a week ago   950      Alfa Romeo 147      2003 manual
27   1408   0       2 days ago   350      Alfa Romeo 147      2003 manual
28    120   2       3 days ago   700      Alfa Romeo 147      2003 manual
29    147   4       2 weeks ago 1450      Alfa Romeo 147      2003 manual
30    111   1       2 weeks ago 1200      Alfa Romeo 147      2003 manual
⋮    ⋮     ⋮        ⋮           ⋮         ⋮                   ⋮    ⋮
8384  151   1       a week ago   950      Zastava Yugo 55     2003 no
8385  196   4       a week ago   350      Zastava Yugo 55     2002 no
8386 3993  41       6 days ago   250      Zastava Yugo 55     2002 no
8387   51   1       3 days ago   750      Zastava Yugo 55     2001 no
8388  131   0       a week ago  3000      Zastava Yugo 55     2000 no
8389 1112  28       5 days ago  1500      Zastava Yugo 55     1999 no
8390  187   1       3 weeks ago  800      Zastava Yugo 55     1999 no
8391  685  12       4 weeks ago  350      Zastava Yugo 55     1992 no
8392  218   1       5 days ago   600      Zastava Yugo 55     1992 no
8393  257   2       3 weeks ago  500      Zastava Yugo 55     1992 no
8394  263   2       3 weeks ago  500      Zastava Yugo 55     1992 no
8395  173   4       4 days ago   280      Zastava Yugo 55     1991 no
8396  390   2       a week ago   180      Zastava Yugo 55     1991 no
8397  354   1       3 weeks ago  800      Zastava Yugo 55     1991 no
8398   21   0       today       1400      Zastava Yugo 55     1990 no
8399   78   1       2 weeks ago  450      Zastava Yugo 55     1990 no
8400 1845  26       2 weeks ago  230      Zastava Yugo 55     1990 no
8401  505   2       a week ago   150      Zastava Yugo 55     1990 no
8402  313   2       a week ago   300      Zastava Yugo 55     1989 no
8403  116   2       yesterday   1000      Zastava Yugo 55     1989 no
8404  306   6       a week ago   600      Zastava Yugo 60     1999 no
8405  149   0       4 days ago  2750      Zastava Yugo 65     1989 no
8406  436   9       3 weeks ago 8500      Zastava Yugo Cabrio 2004 no
8407  166   5       5 days ago   650      Zastava Yugo Ciao   2003 no
8408  449  16       2 weeks ago  850      Zastava Yugo In L   2008 no
8409  131   0       2 weeks ago 1000      Zastava Yugo In L   2006 no
8410  130   1       3 days ago   450      Zastava Yugo In L   2003 no
8411  583  15       a week ago   240      Zastava Yugo Tempo  2002 no
8412  120   2       yesterday    550      Zastava Yugo Tempo  1999 no
8413  259   2       5 days ago   480      Zastava Yugo Tempo  1999 no
     emission_class seats_amount horsepower color    mileage_km
1    NA             NA            NA        NA           NA
2     3              5           106        gray     158546
3     3              5           105        green    337000
4     3              5           120        gray     200000
5    NA              5           116        gray     280000
6    NA              5           105        black    188000
7     4              5           170        black    255000
8     4              5            90        black    214000
9     4              5           120        white    315000
10    4              5           105        black    176853
11   NA              5           105        red      228650
12    5              5           120        black    280000
13    4              5           120        brown    247000
14    3              5           105        gray     158600
15    3              5           120        black    299610
16   NA              5           120        gray     123456
17    3              4           150        black    250750
18   NA              5           141        red      318000
19    4              5           109        silver   220000
20   NA              5           116        gray     350000
21    4              5           150        red      103000
22    3              5           120        red      280560
23    3              5           105        black    280000
24    3              5           116        gray     314458
25    3              5           116        black    300000
26   NA              5           116        teget    300000
27    3              5           102        blue     255000
28    1              5           105        silver   210000
29    3              5           116        blue     285000
30    3              5           120        red      187399
⋮    ⋮              ⋮            ⋮          ⋮        ⋮
8384  1             5            75         red       78567
8385  2             5            60         red       70000
8386  1             5            54         red       47640
8387  1             3            75         red       55575
8388  1             5            55         red       47000
8389 NA             2            63         white     37680
8390  1             5            75         red      100000
8391 NA             5            54         white    150000
8392  3             5            55         red       27720
8393 NA             5            55         blue     220000
8394  1             5            54         white     10000
8395 NA             5            61         red      100000
8396  1             5            75         red      120000
8397  1             4            54         blue      99000
8398  2             5            54         red       35623
8399 NA             5            54         red      134000
8400 NA             5            56         blue          1
8401  2             5            54         teget     35000
8402 NA             5            54         red      164000
8403 NA             5            54         gray      15000
8404  1             3            75         white    100100
8405  2             5            99         orange    86325
8406  1             4            80         bordeaux  96000
8407  3             5            61         white     70000
8408  3             5            60         gray     153716
8409 NA             4            54         green     11000
8410 NA             5            60         red      150152
8411  2             5            54         red       96000
8412  1             5            55         red       75964
8413  3             5            56         red       29883
     engine_capacity_cc type_of_drive doors fuel         car_type  gearbox
1      NA               NA            NA    NA           NA        NA
2    1400               front         2/3   petrol + gas hatchback manual
3    1910               front         2/3   diesel       hatchback manual
4    1600               front         4/5   petrol + gas limousine manual
5    1900               front         2/3   diesel       hatchback manual
6    1600               front         4/5   petrol + gas hatchback manual
7    1929               front         4/5   diesel       hatchback manual
8    1600               front         4/5   petrol + gas hatchback manual
9    1910               front         4/5   diesel       hatchback manual
10   1597               front         4/5   petrol       hatchback manual
11   1600               front         4/5   petrol       hatchback manual
12   1600               front         2/3   petrol + gas hatchback manual
13   1600               front         4/5   petrol + gas hatchback manual
14   1600               front         4/5   petrol       hatchback manual
15   1600               front         2/3   petrol + gas hatchback manual
16   1600               front         4/5   petrol       hatchback manual
17   1910               front         2/3   diesel       hatchback manual
18   1900               front         4/5   diesel       hatchback manual
19   1900               front         4/5   diesel       hatchback manual
20   1910               front         4/5   diesel       hatchback manual
21   1984               front         4/5   petrol       hatchback manual
22   1600               front         2/3   petrol       hatchback manual
23   1600               front         4/5   petrol + gas limousine manual
24   1910               front         4/5   diesel       hatchback manual
25   1910               front         4/5   diesel       hatchback manual
26   1910               front         2/3   diesel       hatchback manual
27   1600               front         4/5   petrol       hatchback manual
28   1600               front         2/3   petrol       hatchback manual
29   1900               front         4/5   diesel       hatchback manual
30   1600               front         4/5   petrol       hatchback manual
⋮    ⋮                  ⋮             ⋮     ⋮            ⋮         ⋮
8384 1111               front         2/3   petrol       hatchback manual
8385 1100               front         2/3   petrol + gas limousine manual
8386 1100               front         2/3   petrol + gas hatchback manual
8387 1100               front         2/3   petrol       hatchback manual
8388 1100               front         2/3   petrol       hatchback manual
8389 1100               front         2/3   petrol       hatchback manual
8390 1000               front         2/3   petrol + gas hatchback manual
8391 1100               front         2/3   petrol       hatchback manual
8392 1100               front         2/3   petrol       hatchback manual
8393 1100               front         2/3   petrol       hatchback manual
8394 1100               front         2/3   petrol       limousine manual
8395 1100               front         2/3   petrol       hatchback manual
8396 1100               front         2/3   petrol       coupe     manual
8397 1116               front         2/3   petrol       hatchback manual
8398 1116               front         2/3   petrol       hatchback manual
8399 1116               front         2/3   petrol + gas coupe     manual
8400 1116               front         2/3   petrol + gas hatchback manual
8401 1100               front         2/3   petrol       hatchback manual
8402 1116               front         2/3   petrol       hatchback manual
8403 1100               front         2/3   petrol       hatchback manual
8404 1200               front         2/3   petrol       coupe     manual
8405 1500               front         2/3   petrol + gas coupe     manual
8406 1242               front         2/3   petrol + gas cabriolet manual
8407 1116               front         2/3   petrol       coupe     manual
8408 1100               front         2/3   petrol       hatchback manual
8409 1100               front         2/3   petrol + gas hatchback manual
8410 1124               front         2/3   petrol       hatchback manual
8411 1100               front         4/5   petrol       limousine manual
8412 1100               front         2/3   petrol       hatchback manual
8413 1116               front         2/3   petrol       limousine manual
     speeds
1    0
2    5
3    5
4    5
5    5
6    5
7    6
8    5
9    6
10   5
11   5
12   5
13   5
14   5
15   5
16   5
17   6
18   6
19   5
20   5
21   5
22   5
23   5
24   5
25   5
26   5
27   5
28   5
29   5
30   5
⋮    ⋮
8384 5
8385 5
8386 5
8387 5
8388 5
8389 5
8390 5
8391 5
8392 5
8393 5
8394 5
8395 5
8396 5
8397 5
8398 5
8399 5
8400 5
8401 5
8402 5
8403 4
8404 5
8405 5
8406 5
8407 5
8408 5
8409 5
8410 5
8411 5
8412 5
8413 0

In [ ]:
list of cars
Alfa Romeo
Audi
BMW
Chevrolet
Chrysler
Citroen
Dacia
Daewoo
Daihatsu
Dodge
Fiat
Ford
Honda
Hyundai
Isuzu
Iveco
Jaguar
Jeep
Kia
Lada
Lancia
Land Rover
Lexus
Maserati
Mazda
Mercedes
MG
Mini
Mitsubishi
Moskwitch
Nissan
Opel
Peugeot
Pontiac
Porsche
Renault
Rover
Saab
Seat
Skoda
Smart
SsangYong
Subaru
Suzuki
Tesla
Toyota
Trabant
UAZ
Volkswagen
Volvo
VW
Wartburg
Zastava

In [26]:
str(cars_raw)

tibble [8,413 × 19] (S3: tbl_df/tbl/data.frame)
 $ views             : int [1:8413] 58 55 136 209 61 196 133 290 2629 89 ...
 $ favorite          : int [1:8413] 0 0 4 1 0 2 1 6 16 0 ...
 $ post_date         : chr [1:8413] "a week ago" "2 days ago" "2 weeks ago" "4 weeks ago" ...
 $ price_eur         : int [1:8413] 1100 1100 950 500 111 2300 3500 2150 1350 2000 ...
 $ car_name          : chr [1:8413] "Alfa Romeo 11.9" "Alfa Romeo 145" "Alfa Romeo 145" "Alfa Romeo 146" ...
 $ year              : int [1:8413] 2002 2000 1999 2000 2024 2008 2008 2008 2008 2007 ...
 $ ac                : chr [1:8413] NA "manual" "manual" "manual" ...
 $ emission_class    : int [1:8413] NA 3 3 3 NA NA 4 4 4 4 ...
 $ seats_amount      : int [1:8413] NA 5 5 5 5 5 5 5 5 5 ...
 $ horsepower        : int [1:8413] NA 106 105 120 116 105 170 90 120 105 ...
 $ color             : chr [1:8413] NA "gray" "green" "gray" ...
 $ mileage_km        : int [1:8413] NA 158546 337000 200000 280000 188000 255000 214000 315000 176853 ...
 $ engine_capacity_cc: int [1:8413] NA 1400 1910 1600 1900 1600 1929 1600 1910 1597 ...
 $ type_of_drive     : chr [1:8413] NA "front" "front" "front" ...
 $ doors             : chr [1:8413] NA "2/3" "2/3" "4/5" ...
 $ fuel              : chr [1:8413] NA "petrol + gas" "diesel" "petrol + gas" ...
 $ car_type          : chr [1:8413] NA "hatchback" "hatchback" "limousine" ...
 $ gearbox           : chr [1:8413] NA "manual" "manual" "manual" ...
 $ speeds            : int [1:8413] 0 5 5 5 5 5 6 5 6 5 ...

In [27]:
summary(cars_raw)

     views            favorite        post_date           price_eur
 Min.   :    0.0   Min.   :  0.000   Length:8413        Min.   :  100
 1st Qu.:   61.0   1st Qu.:  0.000   Class :character   1st Qu.: 1600
 Median :  114.0   Median :  1.000   Mode  :character   Median : 3300
 Mean   :  308.7   Mean   :  2.672                      Mean   : 4848
 3rd Qu.:  245.0   3rd Qu.:  3.000                      3rd Qu.: 5950
 Max.   :27770.0   Max.   :151.000                      Max.   :82000

   car_name              year           ac            emission_class
 Length:8413        Min.   :1960   Length:8413        Min.   :1.000
 Class :character   1st Qu.:2003   Class :character   1st Qu.:3.000
 Mode  :character   Median :2006   Mode  :character   Median :4.000
                    Mean   :2006                      Mean   :3.962
                    3rd Qu.:2010                      3rd Qu.:5.000
                    Max.   :2024                      Max.   :6.000
                                                      NA's   :1337
  seats_amount    horsepower       color             mileage_km
 Min.   :2.00   Min.   :  1.0   Length:8413        Min.   :        1
 1st Qu.:5.00   1st Qu.: 82.0   Class :character   1st Qu.:   176676
 Median :5.00   Median :109.0   Mode  :character   Median :   220000
 Mean   :4.94   Mean   :115.4                      Mean   :   296820
 3rd Qu.:5.00   3rd Qu.:140.0                      3rd Qu.:   270000
 Max.   :9.00   Max.   :900.0                      Max.   :111111111
 NA's   :10     NA's   :10                         NA's   :14
 engine_capacity_cc type_of_drive         doors               fuel
 Min.   :  100      Length:8413        Length:8413        Length:8413
 1st Qu.: 1400      Class :character   Class :character   Class :character
 Median : 1700      Mode  :character   Mode  :character   Mode  :character
 Mean   : 1725
 3rd Qu.: 1995
 Max.   :10000
 NA's   :10
   car_type           gearbox              speeds
 Length:8413        Length:8413        Min.   :0.000
 Class :character   Class :character   1st Qu.:5.000
 Mode  :character   Mode  :character   Median :5.000
                                       Mean   :4.497
                                       3rd Qu.:6.000
                                       Max.   :6.000